spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:parkinglot
    username: oliver
    password: w665570@
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8090
